[server]
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false

[theme]
base="dark"
primaryColor="#8742f5"
backgroundColor="#1e1e1e"
secondaryBackgroundColor="#2d2d2d"
textColor="#e0e0e0"